
package mypackage;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "BankWS", targetNamespace = "http://ws.mb.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface BankWS {


    /**
     * 
     * @param account
     * @return
     *     returns double
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "conversionEuroToXAF", targetNamespace = "http://ws.mb.com/", className = "mypackage.ConversionEuroToXAF")
    @ResponseWrapper(localName = "conversionEuroToXAFResponse", targetNamespace = "http://ws.mb.com/", className = "mypackage.ConversionEuroToXAFResponse")
    @Action(input = "http://ws.mb.com/BankWS/conversionEuroToXAFRequest", output = "http://ws.mb.com/BankWS/conversionEuroToXAFResponse")
    public double conversionEuroToXAF(
        @WebParam(name = "account", targetNamespace = "")
        double account);

    /**
     * 
     * @param code
     * @return
     *     returns mypackage.Account
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAcccount", targetNamespace = "http://ws.mb.com/", className = "mypackage.GetAcccount")
    @ResponseWrapper(localName = "getAcccountResponse", targetNamespace = "http://ws.mb.com/", className = "mypackage.GetAcccountResponse")
    @Action(input = "http://ws.mb.com/BankWS/getAcccountRequest", output = "http://ws.mb.com/BankWS/getAcccountResponse")
    public Account getAcccount(
        @WebParam(name = "code", targetNamespace = "")
        Long code);

    /**
     * 
     * @return
     *     returns java.util.List<mypackage.Account>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "listAccount", targetNamespace = "http://ws.mb.com/", className = "mypackage.ListAccount")
    @ResponseWrapper(localName = "listAccountResponse", targetNamespace = "http://ws.mb.com/", className = "mypackage.ListAccountResponse")
    @Action(input = "http://ws.mb.com/BankWS/listAccountRequest", output = "http://ws.mb.com/BankWS/listAccountResponse")
    public List<Account> listAccount();

}
